### ISSUE TITLE
Some missing files/modules? (SimpleNet, layers, preprocessing)

### ISSUE THREAD

**Issue by codezakh** [gkoumasd/MSAF#1]
Thanks for providing this code! I'm trying to run the simple baselines: specifically EF-LSTM and LF-LSTM, and they depend on class called `SimpleNet`, which isn't in the repo. Similarly, the transformer-based models are trying to import from a `layers` module and some of the io code from a module called `proprocessing`. Will you be making the code for these classes/modules/files available?

**Comment by gkoumasd** [comment]
The repository has been updated accordinly.
